// Code generated by MockGen. DO NOT EDIT.
// Source: validator_client.go
//
// Generated by this command:
//
//	mockgen -source=validator_client.go -destination=mocks/mock_validator_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ids "github.com/ryt-io/ryt-v2/ids"
	validators "github.com/ryt-io/ryt-v2/snow/validators"
	platformvm "github.com/ryt-io/ryt-v2/vms/platformvm"
	gomock "go.uber.org/mock/gomock"
)

// MockCanonicalValidatorState is a mock of CanonicalValidatorState interface.
type MockCanonicalValidatorState struct {
	ctrl     *gomock.Controller
	recorder *MockCanonicalValidatorStateMockRecorder
	isgomock struct{}
}

// MockCanonicalValidatorStateMockRecorder is the mock recorder for MockCanonicalValidatorState.
type MockCanonicalValidatorStateMockRecorder struct {
	mock *MockCanonicalValidatorState
}

// NewMockCanonicalValidatorState creates a new mock instance.
func NewMockCanonicalValidatorState(ctrl *gomock.Controller) *MockCanonicalValidatorState {
	mock := &MockCanonicalValidatorState{ctrl: ctrl}
	mock.recorder = &MockCanonicalValidatorStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCanonicalValidatorState) EXPECT() *MockCanonicalValidatorStateMockRecorder {
	return m.recorder
}

// GetAllValidatorSets mocks base method.
func (m *MockCanonicalValidatorState) GetAllValidatorSets(ctx context.Context, pchainHeight uint64) (map[ids.ID]validators.WarpSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllValidatorSets", ctx, pchainHeight)
	ret0, _ := ret[0].(map[ids.ID]validators.WarpSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllValidatorSets indicates an expected call of GetAllValidatorSets.
func (mr *MockCanonicalValidatorStateMockRecorder) GetAllValidatorSets(ctx, pchainHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllValidatorSets", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetAllValidatorSets), ctx, pchainHeight)
}

// GetCurrentValidators mocks base method.
func (m *MockCanonicalValidatorState) GetCurrentValidators(ctx context.Context, subnetID ids.ID) ([]platformvm.ClientPermissionlessValidator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValidators", ctx, subnetID)
	ret0, _ := ret[0].([]platformvm.ClientPermissionlessValidator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentValidators indicates an expected call of GetCurrentValidators.
func (mr *MockCanonicalValidatorStateMockRecorder) GetCurrentValidators(ctx, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValidators", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetCurrentValidators), ctx, subnetID)
}

// GetLatestHeight mocks base method.
func (m *MockCanonicalValidatorState) GetLatestHeight(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHeight", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestHeight indicates an expected call of GetLatestHeight.
func (mr *MockCanonicalValidatorStateMockRecorder) GetLatestHeight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHeight", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetLatestHeight), ctx)
}

// GetProposedValidators mocks base method.
func (m *MockCanonicalValidatorState) GetProposedValidators(ctx context.Context, subnetID ids.ID) (validators.WarpSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProposedValidators", ctx, subnetID)
	ret0, _ := ret[0].(validators.WarpSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProposedValidators indicates an expected call of GetProposedValidators.
func (mr *MockCanonicalValidatorStateMockRecorder) GetProposedValidators(ctx, subnetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProposedValidators", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetProposedValidators), ctx, subnetID)
}

// GetSubnet mocks base method.
func (m *MockCanonicalValidatorState) GetSubnet(ctx context.Context, blockchainID ids.ID) (platformvm.GetSubnetClientResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnet", ctx, blockchainID)
	ret0, _ := ret[0].(platformvm.GetSubnetClientResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnet indicates an expected call of GetSubnet.
func (mr *MockCanonicalValidatorStateMockRecorder) GetSubnet(ctx, blockchainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnet", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetSubnet), ctx, blockchainID)
}

// GetSubnetID mocks base method.
func (m *MockCanonicalValidatorState) GetSubnetID(ctx context.Context, blockchainID ids.ID) (ids.ID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetID", ctx, blockchainID)
	ret0, _ := ret[0].(ids.ID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetID indicates an expected call of GetSubnetID.
func (mr *MockCanonicalValidatorStateMockRecorder) GetSubnetID(ctx, blockchainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetID", reflect.TypeOf((*MockCanonicalValidatorState)(nil).GetSubnetID), ctx, blockchainID)
}
