// Code generated by MockGen. DO NOT EDIT.
// Source: destination_client.go
//
// Generated by this command:
//
//	mockgen -source=destination_client.go -destination=./mocks/mock_destination_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ids "github.com/ryt-io/ryt-v2/ids"
	set "github.com/ryt-io/ryt-v2/utils/set"
	warp "github.com/ryt-io/ryt-v2/vms/platformvm/warp"
	evm "github.com/ryt-io/icm-services/vms/evm"
	common "github.com/ryt-io/libevm/common"
	types "github.com/ryt-io/libevm/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDestinationClient is a mock of DestinationClient interface.
type MockDestinationClient struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationClientMockRecorder
	isgomock struct{}
}

// MockDestinationClientMockRecorder is the mock recorder for MockDestinationClient.
type MockDestinationClientMockRecorder struct {
	mock *MockDestinationClient
}

// NewMockDestinationClient creates a new mock instance.
func NewMockDestinationClient(ctrl *gomock.Controller) *MockDestinationClient {
	mock := &MockDestinationClient{ctrl: ctrl}
	mock.recorder = &MockDestinationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationClient) EXPECT() *MockDestinationClientMockRecorder {
	return m.recorder
}

// BlockGasLimit mocks base method.
func (m *MockDestinationClient) BlockGasLimit() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockGasLimit")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// BlockGasLimit indicates an expected call of BlockGasLimit.
func (mr *MockDestinationClientMockRecorder) BlockGasLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockGasLimit", reflect.TypeOf((*MockDestinationClient)(nil).BlockGasLimit))
}

// Client mocks base method.
func (m *MockDestinationClient) Client() evm.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(evm.Client)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDestinationClientMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDestinationClient)(nil).Client))
}

// DestinationBlockchainID mocks base method.
func (m *MockDestinationClient) DestinationBlockchainID() ids.ID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestinationBlockchainID")
	ret0, _ := ret[0].(ids.ID)
	return ret0
}

// DestinationBlockchainID indicates an expected call of DestinationBlockchainID.
func (mr *MockDestinationClientMockRecorder) DestinationBlockchainID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestinationBlockchainID", reflect.TypeOf((*MockDestinationClient)(nil).DestinationBlockchainID))
}

// GetPChainHeightForDestination mocks base method.
func (m *MockDestinationClient) GetPChainHeightForDestination(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPChainHeightForDestination", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPChainHeightForDestination indicates an expected call of GetPChainHeightForDestination.
func (mr *MockDestinationClientMockRecorder) GetPChainHeightForDestination(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPChainHeightForDestination", reflect.TypeOf((*MockDestinationClient)(nil).GetPChainHeightForDestination), ctx)
}

// GetRPCEndpointURL mocks base method.
func (m *MockDestinationClient) GetRPCEndpointURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRPCEndpointURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRPCEndpointURL indicates an expected call of GetRPCEndpointURL.
func (mr *MockDestinationClientMockRecorder) GetRPCEndpointURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRPCEndpointURL", reflect.TypeOf((*MockDestinationClient)(nil).GetRPCEndpointURL))
}

// SendTx mocks base method.
func (m *MockDestinationClient) SendTx(signedMessage *warp.Message, deliverers set.Set[common.Address], toAddress string, gasLimit uint64, callData []byte) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTx", signedMessage, deliverers, toAddress, gasLimit, callData)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTx indicates an expected call of SendTx.
func (mr *MockDestinationClientMockRecorder) SendTx(signedMessage, deliverers, toAddress, gasLimit, callData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTx", reflect.TypeOf((*MockDestinationClient)(nil).SendTx), signedMessage, deliverers, toAddress, gasLimit, callData)
}

// SenderAddresses mocks base method.
func (m *MockDestinationClient) SenderAddresses() []common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SenderAddresses")
	ret0, _ := ret[0].([]common.Address)
	return ret0
}

// SenderAddresses indicates an expected call of SenderAddresses.
func (mr *MockDestinationClientMockRecorder) SenderAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SenderAddresses", reflect.TypeOf((*MockDestinationClient)(nil).SenderAddresses))
}
