// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ryt-io/icm-services/vms/evm (interfaces: DestinationRPCClient)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_destination_rpc_client.go -package=mocks github.com/ryt-io/icm-services/vms/evm DestinationRPCClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	ethereum "github.com/ava-labs/libevm"
	common "github.com/ava-labs/libevm/common"
	types "github.com/ava-labs/libevm/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDestinationRPCClient is a mock of DestinationRPCClient interface.
type MockDestinationRPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationRPCClientMockRecorder
	isgomock struct{}
}

// MockDestinationRPCClientMockRecorder is the mock recorder for MockDestinationRPCClient.
type MockDestinationRPCClientMockRecorder struct {
	mock *MockDestinationRPCClient
}

// NewMockDestinationRPCClient creates a new mock instance.
func NewMockDestinationRPCClient(ctrl *gomock.Controller) *MockDestinationRPCClient {
	mock := &MockDestinationRPCClient{ctrl: ctrl}
	mock.recorder = &MockDestinationRPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestinationRPCClient) EXPECT() *MockDestinationRPCClientMockRecorder {
	return m.recorder
}

// BlockByNumber mocks base method.
func (m *MockDestinationRPCClient) BlockByNumber(ctx context.Context, blockNumber *big.Int) (*types.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockByNumber", ctx, blockNumber)
	ret0, _ := ret[0].(*types.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockByNumber indicates an expected call of BlockByNumber.
func (mr *MockDestinationRPCClientMockRecorder) BlockByNumber(ctx, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockByNumber", reflect.TypeOf((*MockDestinationRPCClient)(nil).BlockByNumber), ctx, blockNumber)
}

// BlockNumber mocks base method.
func (m *MockDestinationRPCClient) BlockNumber(ctx context.Context) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockNumber", ctx)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockNumber indicates an expected call of BlockNumber.
func (mr *MockDestinationRPCClientMockRecorder) BlockNumber(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockNumber", reflect.TypeOf((*MockDestinationRPCClient)(nil).BlockNumber), ctx)
}

// CallContract mocks base method.
func (m *MockDestinationRPCClient) CallContract(ctx context.Context, msg ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallContract", ctx, msg, blockNumber)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallContract indicates an expected call of CallContract.
func (mr *MockDestinationRPCClientMockRecorder) CallContract(ctx, msg, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallContract", reflect.TypeOf((*MockDestinationRPCClient)(nil).CallContract), ctx, msg, blockNumber)
}

// ChainID mocks base method.
func (m *MockDestinationRPCClient) ChainID(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainID", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainID indicates an expected call of ChainID.
func (mr *MockDestinationRPCClientMockRecorder) ChainID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainID", reflect.TypeOf((*MockDestinationRPCClient)(nil).ChainID), ctx)
}

// EstimateBaseFee mocks base method.
func (m *MockDestinationRPCClient) EstimateBaseFee(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimateBaseFee", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EstimateBaseFee indicates an expected call of EstimateBaseFee.
func (mr *MockDestinationRPCClientMockRecorder) EstimateBaseFee(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimateBaseFee", reflect.TypeOf((*MockDestinationRPCClient)(nil).EstimateBaseFee), ctx)
}

// NonceAt mocks base method.
func (m *MockDestinationRPCClient) NonceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NonceAt", ctx, account, blockNumber)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NonceAt indicates an expected call of NonceAt.
func (mr *MockDestinationRPCClientMockRecorder) NonceAt(ctx, account, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NonceAt", reflect.TypeOf((*MockDestinationRPCClient)(nil).NonceAt), ctx, account, blockNumber)
}

// SendTransaction mocks base method.
func (m *MockDestinationRPCClient) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTransaction", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockDestinationRPCClientMockRecorder) SendTransaction(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockDestinationRPCClient)(nil).SendTransaction), ctx, tx)
}

// SuggestGasTipCap mocks base method.
func (m *MockDestinationRPCClient) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuggestGasTipCap", ctx)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuggestGasTipCap indicates an expected call of SuggestGasTipCap.
func (mr *MockDestinationRPCClientMockRecorder) SuggestGasTipCap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuggestGasTipCap", reflect.TypeOf((*MockDestinationRPCClient)(nil).SuggestGasTipCap), ctx)
}

// TransactionReceipt mocks base method.
func (m *MockDestinationRPCClient) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionReceipt", ctx, txHash)
	ret0, _ := ret[0].(*types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionReceipt indicates an expected call of TransactionReceipt.
func (mr *MockDestinationRPCClientMockRecorder) TransactionReceipt(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionReceipt", reflect.TypeOf((*MockDestinationRPCClient)(nil).TransactionReceipt), ctx, txHash)
}
