// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: decider/decider.proto

package decider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShouldSendMessageRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	NetworkId           uint32                 `protobuf:"varint,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	SourceChainId       []byte                 `protobuf:"bytes,2,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	Payload             []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	BytesRepresentation []byte                 `protobuf:"bytes,4,opt,name=bytes_representation,json=bytesRepresentation,proto3" json:"bytes_representation,omitempty"`
	Id                  []byte                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ShouldSendMessageRequest) Reset() {
	*x = ShouldSendMessageRequest{}
	mi := &file_decider_decider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShouldSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldSendMessageRequest) ProtoMessage() {}

func (x *ShouldSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_decider_decider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldSendMessageRequest.ProtoReflect.Descriptor instead.
func (*ShouldSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_decider_decider_proto_rawDescGZIP(), []int{0}
}

func (x *ShouldSendMessageRequest) GetNetworkId() uint32 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *ShouldSendMessageRequest) GetSourceChainId() []byte {
	if x != nil {
		return x.SourceChainId
	}
	return nil
}

func (x *ShouldSendMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ShouldSendMessageRequest) GetBytesRepresentation() []byte {
	if x != nil {
		return x.BytesRepresentation
	}
	return nil
}

func (x *ShouldSendMessageRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type ShouldSendMessageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ShouldSendMessage bool                   `protobuf:"varint,1,opt,name=should_send_message,json=shouldSendMessage,proto3" json:"should_send_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShouldSendMessageResponse) Reset() {
	*x = ShouldSendMessageResponse{}
	mi := &file_decider_decider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShouldSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShouldSendMessageResponse) ProtoMessage() {}

func (x *ShouldSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_decider_decider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShouldSendMessageResponse.ProtoReflect.Descriptor instead.
func (*ShouldSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_decider_decider_proto_rawDescGZIP(), []int{1}
}

func (x *ShouldSendMessageResponse) GetShouldSendMessage() bool {
	if x != nil {
		return x.ShouldSendMessage
	}
	return false
}

var File_decider_decider_proto protoreflect.FileDescriptor

const file_decider_decider_proto_rawDesc = "" +
	"\n" +
	"\x15decider/decider.proto\x12\adecider\"\xbe\x01\n" +
	"\x18ShouldSendMessageRequest\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\rR\tnetworkId\x12&\n" +
	"\x0fsource_chain_id\x18\x02 \x01(\fR\rsourceChainId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x121\n" +
	"\x14bytes_representation\x18\x04 \x01(\fR\x13bytesRepresentation\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\fR\x02id\"K\n" +
	"\x19ShouldSendMessageResponse\x12.\n" +
	"\x13should_send_message\x18\x01 \x01(\bR\x11shouldSendMessage2l\n" +
	"\x0eDeciderService\x12Z\n" +
	"\x11ShouldSendMessage\x12!.decider.ShouldSendMessageRequest\x1a\".decider.ShouldSendMessageResponseB3Z1github.com/ryt-io/icm-services/proto/pb/deciderb\x06proto3"

var (
	file_decider_decider_proto_rawDescOnce sync.Once
	file_decider_decider_proto_rawDescData []byte
)

func file_decider_decider_proto_rawDescGZIP() []byte {
	file_decider_decider_proto_rawDescOnce.Do(func() {
		file_decider_decider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_decider_decider_proto_rawDesc), len(file_decider_decider_proto_rawDesc)))
	})
	return file_decider_decider_proto_rawDescData
}

var file_decider_decider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_decider_decider_proto_goTypes = []any{
	(*ShouldSendMessageRequest)(nil),  // 0: decider.ShouldSendMessageRequest
	(*ShouldSendMessageResponse)(nil), // 1: decider.ShouldSendMessageResponse
}
var file_decider_decider_proto_depIdxs = []int32{
	0, // 0: decider.DeciderService.ShouldSendMessage:input_type -> decider.ShouldSendMessageRequest
	1, // 1: decider.DeciderService.ShouldSendMessage:output_type -> decider.ShouldSendMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_decider_decider_proto_init() }
func file_decider_decider_proto_init() {
	if File_decider_decider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decider_decider_proto_rawDesc), len(file_decider_decider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decider_decider_proto_goTypes,
		DependencyIndexes: file_decider_decider_proto_depIdxs,
		MessageInfos:      file_decider_decider_proto_msgTypes,
	}.Build()
	File_decider_decider_proto = out.File
	file_decider_decider_proto_goTypes = nil
	file_decider_decider_proto_depIdxs = nil
}
